### ISSUE TITLE
Some memo for code review

### ISSUE THREAD

**Issue by Scisaga** [chhsiao90/nitmproxy#1]
Thanks for sharing. I need build a personalized multi layer proxy server and reviewed several related projects on github, here's some memo, just personal understanding.

1. You can choose either http or socks proxy mode, better way is to add protocol detector enable both mode supported on one port.
2. Use enum type in NitmProxyMaster to achieve handler selecting mechanism, which complicate code structure and more confuse for me to track logic flows.
3. Some class like HttpProxyHandler/TlsHandler/Http1FrontedHander not clearly defined, some cyclic calls exist, split functions by usage scenario and re-construct handlers by single responsibility principle could be better.

**Comment by chhsiao90** [comment]
Totally agreed with your opinions, currently the structure is not very ideal to understand or maintain. And thanks for your review!
