### ISSUE TITLE
Http1BackendHandler & DelayOutboundHandler

### ISSUE THREAD

**Issue by Scisaga** [chhsiao90/nitmproxy#2]
In Http1BackendHandler, DelayOutboundHandler is added to filtering msg type and holding back FullHttpRequest.  under what circumstances need to do so? and what's the outcome, could u give me some hints? thanks @chhsiao90

**Comment by chhsiao90** [comment]
Hi @Scisaga -
I'm not really sure, I remembered that sometimes the outbound handler is not ready to receive the http request, so I add a delay handler to check and send when the outbound channel is active. I forgot in what circumstances it would happen.
