### ISSUE TITLE
Support for Transparent Proxy

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#23]
I wanted to see if the transparent proxy feature is added to NITM. Basically, in windows firewall driver, the traffic can be directed to a transparent proxy (with intact dest IP and port). To support that, I was thinking of the following changes:

1. Add proxy/TransparentProxyHandler which adds tlsFrontendHandler in the pipeline (if TLS is not detected, it auto switches to HTTP1 anyway). 
2. Modify Http1FrontendHandler to essentially replicate handleHttpProxyConnection. We are duplicating the request anyway.

```
        if (master.config().getProxyMode() == ProxyMode.HTTP && !tunneled) {
            if (request.method() == HttpMethod.CONNECT) {
                handleTunnelProxyConnection(ctx, request);
            } else {
                handleHttpProxyConnection(ctx, request);
            }
        } else if (master.config().getProxyMode() == ProxyMode.TRANSPARENT) {
            handleHttpProxyConnection(ctx, request);
        } else {
            LOGGER.debug("{} : {}", connectionContext, request);
            connectionContext.serverChannel().writeAndFlush(ReferenceCountUtil.retain(request));
        }

```   
3. Add caching of client certificates that are generated for performance. 

Please let me know your thoughts on this.

**Comment by chhsiao90** [comment]
Hi @abbasvalliani 

Sounds great to have transparent proxy feature. The proposal looks good to me. Do you want to have a pull request for this?

I create separated issue #24 for the point 3.

**Comment by abbasvalliani** [comment]
Thanks. Testing it now and will submit a PR shortly. BTW, fantastic work on the proxy.

**Comment by abbasvalliani** [comment]
Just submitted a PR. Tested it against Linux and Mac. Had to fix cert generation (https://support.apple.com/en-us/HT210176) for Mac OS. 

The implementation doesn't depend on destination IP/Port. HTTP target is determined by Host HTTP header and SSL host is determined by SNI lookup. Doesn't support SSL on a different port (defaults to 443). Will add more documentation on how to port forward to Linux and Mac shortly.

**Comment by abbasvalliani** [comment]
Just updated the repo with your comments.

**Comment by chhsiao90** [comment]
Fixed by #27

**Comment by chhsiao90** [comment]
v1.2.0 was released!

**Comment by abbasvalliani** [comment]
Great news! Can you upload to mvnrepository as well? Thanks!

On 5/13/2021 9:26:52 PM, Chun-Han, Hsiao ***@***.***> wrote:
v1.2.0 was released!

**Comment by chhsiao90** [comment]
It was just released, it might takes hours to sync to the maven central, maybe you can check it later!
