### ISSUE TITLE
Add support for non file based keys/certificates to create NitmProxy

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#29]
I have a case where the certificates will be created on the fly and I need to create a new instance of NitmProxy inside a java program. NtimProxyConfig currently uses a File for key and certs. My recommendation would be to change the signature to allow for X509CertificateHolder and PEMKeyPair or KeyPair. 

Proposal is as follows:
CertUtil -> change signature of newCert to take a X509Cert and KeyPair

NitmProxyConfig -> remove file based cert/keys. Instead introduce another constructor which allows for file based keys and certs which get transformed into X509Cert and KeyPair

NitmProxy -> Call the NitmProxyConfig constructor which takes file based certs/keys

**Comment by abbasvalliani** [comment]
Thanks for the quick turn around.

**Comment by chhsiao90** [comment]
v1.2.0 was released!
