### ISSUE TITLE
Adding interceptors - Skip Backend Handler

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#36]
There may be a case need of interceptors for e.g. 

A simple Uri/host or request body interceptor based on a match (callback with regex support for url/host match). The request may be intercepted and a response can be constructed. No request needs to be made to the backend handler. 

This can be useful to provide HTML responses on blocked pages.

**Comment by chhsiao90** [comment]
Hi @abbasvalliani 

I'm going to implement this feature, it should be available soon.

**Comment by abbasvalliani** [comment]
Fantastic. I could use it immediately! If there is way to allow modification to request and response objects before backend handler and also after the backendhandler, that would be fantastic. 

More specialized functions for host and Uri matches (using callbacks) could provide out of the box helpers that would be very convenient to use.
