### ISSUE TITLE
Handling non HTTP data

### ISSUE THREAD

**Issue by koh-osug** [chhsiao90/nitmproxy#8]
It seems that the TlsBackendHandler is just supporting HTTP. What has to be done to make it work also for SMTP and IMAP, etc? Is the assumption correct that in `com.github.chhsiaoninety.nitmproxy.handler.protocol.tls.TlsBackendHandler.AlpnHandler#configurePipeline` the `ForwardHandler" has to be used then?

**Comment by chhsiao90** [comment]
Yeah, the purpose of the forward handler is to forwarding traffic which the protocol is not supported yet by the nitmproxy.

Is the alpn extension always provided for this kind of protocols? If so, I guessed they can be supported by add the forward handler to the pipeline in the else condition of `AlpnHandler#configurePipeline`.

**Comment by koh-osug** [comment]
I guess, ALPN makes only sense for HTTP. In other protocols it is not included  I thought the else branch is also reached if no ALPN extension is not found and `connectionContext.tlsCtx().isNegotiated()` would return false then. I'm not sure how to handle the fallback protocol and how to detect if actually HTTP is used or any other protocol like SMTP or IMAP which would then be handled by the `ForwardHandler`. Any ideas how to detect this?
What are the benefits of the special HTTP(1|2)BackendHandlers over just using the ForwardHandler for everything?

**Comment by chhsiao90** [comment]
The nitmproxy is netty-based [mitmproxy](https://github.com/mitmproxy/mitmproxy) (only few features support).

There is a lot of thing the proxy can do when it can intercept the network traffic.

**Comment by koh-osug** [comment]
Yes, a lot can be done.  AFAIK mitmproxy just acts as an HTTP proxy and does not support SOCKS. And a Python implementation is unsupported for Android. These are the benefits of nitmproxy. I will try then to find a solution on myself being executed instead or in addition to the ALPNHandler.

**Comment by chhsiao90** [comment]
I guessed the easiest way is to switch protocol based on the destination port. Use different handler for different port.

Maybe nitmproxy can have some interface for extending this features.

**Comment by kaoh** [comment]
I would propose the following: 

1. In `com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsFrontendHandler.AlpnHandler#configurePipeline` (neither HTTP1 nor HTTP2 detected) and in `com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsFrontendHandler.DetectSslHandler#onLookupComplete` (no TLS detected) add a `ProtocolDetectorHandler` to the pipeline.
2. The `ProtocolDetectorHandler` would detect e.g. traffic starting with "HTTP" and route it to the `http1FrontendHandler`, similar with HTTP2, other protocols would be routed to a binary handler. This would be some kind of `SimpleChannelInboundHandler<ByteBuf>` implementation.
3. Similar treatment would be done in `com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsBackendHandler.AlpnHandler#configurePipeline` if neither HTTP1 or HTTP 2 is used and in `com.github.chhsiao90.nitmproxy.handler.protocol.tls.TlsBackendHandler#handlerAdded` if no TLS is used.
4. A new Logger must be added also supporting binary logging.

If this makes sense I can give it a try and create a pull request or if you think you are faster you are welcome to add it, too.

**Comment by chhsiao90** [comment]
The proposal looks good to me.

* The ProtocolDetectorHandler should extend ByteToMessageDecoder just like how [SslClientHelloHandler](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/ssl/SslClientHelloHandler.java) do to make sure the inbound will be forwarded to the configured handler
* I think we don't need to detect HTTP/2 in this handler, the ALPN should be provided while using HTTP/2
* The ForwardHandler should be a good choice for those unsupported protocols
* I don't have any idea about the binary logging, I think the log will be too verbose if we just print all the payload in hex string.

Please go ahead to create a pull request for this! I suggest we can have a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for this!

**Comment by abbasvalliani** [comment]
@kaoh Are you actively working on it? I have a similar need but don't want to duplicate the work.

**Comment by kaoh** [comment]
It is on my TO DO list and will definitively come, but currently I'm under heavy load, so I assume this can take a while. If you are familiar with netty, then this might just be just one day of programming or less to implement this feature. You are welcome to engage.

**Comment by chhsiao90** [comment]
nitmproxy v1.1.1 released. I can only test on simple scenario, can you help to check if #26 works? Thanks!

We also support custom protocol detector by:
```
config.setDetectors(...);
```

**Comment by chhsiao90** [comment]
* ProtocolSelectHandler was used when TLS was disabled
* AlpnHandler from the TlsFrontendHandler was used when TLS was enabled.
* In most cases, HTTP2 requires TLS enabled with alpn extension, please let me know if that's not your case
* When http1 detected, we use Http1ProtocolDetector, otherwise, forwarding the network traffic
* I will check why forward handler doesn't work

**Comment by chhsiao90** [comment]
Hi @koh-osug

I guessed the reason why it failed on IMAP and Thunderbird is that they are using TLS without providing alpn, and we fallback to HTTP1  when there is no alpn extension.

How about we fallback to forward handler when no alpn provided?

**Comment by chhsiao90** [comment]
I already have another PR #28 for this improvement.

**Comment by koh-osug** [comment]
AFAIK ALPN is only used no HTTP2/1, no other protocol is using this (at least IMAP and SMTP and POP) negotiation mechanism. So, the logic might be to check for ALPN, and then detect if it is HTTP1 or finally using the forward handler.

**Comment by koh-osug** [comment]
The patch looks good. Thanks for your work, I will test it.

**Comment by koh-osug** [comment]
I have tested it. It works. I have added a logger dumping also the forwarded contents, I will use a pull request draft for the logger.
