### ISSUE TITLE
Resource Leak - alloc but no release

### ISSUE THREAD

**Issue by abbasvalliani** [chhsiao90/nitmproxy#95]
### #1 - SSL Handlers

In TLSBackEndHandler and TLSFrontEndHandler, 

alloc is done but never released. Could this be a source of memory leak? The leak detector is pointing to the sslhandler.

```
    /**
     * Configure for ssl.
     *
     * @param ctx the channel handler context
     * @throws SSLException if ssl failure
     */
    private void configSsl(ChannelHandlerContext ctx) throws SSLException {
        **SslHandler sslHandler = sslHandler(ctx.alloc());**
        ctx.pipeline()
            .addBefore(ctx.name(), null, sslHandler)
            .addBefore(ctx.name(), null, new AlpnHandler(ctx, getFallbackProtocol()));
    }
```

### #2 - Other Handlers
Single stack (there is a message leak with the stack below)
	com.github.chhsiao90.nitmproxy.handler.protocol.http2.Http2FrontendHandler.write(Http2FrontendHandler.java:66)
	com.github.chhsiao90.nitmproxy.handler.protocol.http2.Http2EventHandler.write(Http2EventHandler.java:69)
        com.github.chhsiao90.nitmproxy.handler.protocol.http2.Http2BackendHandler.onDataRead(Http2BackendHandler.java:105)

**Comment by chhsiao90** [comment]
I believe that it's same issue #78. I will try to investigate this issue.

**Comment by chhsiao90** [comment]
Close issue for now as it duplicates #78 .
